INTERFACE zif_biz_sources_types
  PUBLIC .

  TYPES:
    BEGIN OF key_struct,
      key_field           TYPE char32,
      operator            TYPE char2,
      key_condition_value TYPE char255,
      binding_operator    TYPE char3, "AND | OR
    END OF key_struct,
    BEGIN OF generic_data_structure,
      attribute TYPE string,
      value     TYPE string,
    END OF generic_data_structure,
    BEGIN OF ENUM supported_tables,
      zpf_agent_prps,
      zbiz_agent ,
      zbz_data_source,
      zpf_data_src_sub,
      zpf_dt_src_agent,
      zpf_prog_lang,
      zpf_src_endpoint,
      zbz_subscription,
    END OF ENUM supported_tables,
    where_condition         TYPE STANDARD TABLE OF key_struct WITH EMPTY KEY,
    generic_data_attributes TYPE STANDARD TABLE OF generic_data_structure WITH EMPTY KEY,
    BEGIN OF ENUM supported_views,
      z_c_agent,
      z_c_datasrcssubs,
      z_c_endpoints,
      z_c_subscription,
      z_i_agent_purpose,
      z_i_agent,
      z_i_datasrcssubs,
      z_i_prog_lang,
      z_i_srcendpoint,
      z_i_subscription,
    END OF ENUM supported_views,
    BEGIN OF ENUM update_error_statuses,
      ok_status,
      exception_in_select,
      error_in_select,
      exception_in_update,
      error_in_update,
      unknown_exception,
      too_many_lines,
      casting_exception,
      component_mapping_exception,
    END OF ENUM update_error_statuses.

ENDINTERFACE.
