CLASS zcl_class_jm1 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES : IF_OO_ADT_CLASSRUN.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_class_jm1 IMPLEMENTATION.
  METHOD if_oo_adt_classrun~main.
        out->write('Hello World!').
  ENDMETHOD.

ENDCLASS.
