CLASS LHC_INVENTORY DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEINVENTORYID FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  Inventory~CalculateInventoryID .
ENDCLASS.

CLASS LHC_INVENTORY IMPLEMENTATION.
  METHOD CALCULATEINVENTORYID.
  ENDMETHOD.
ENDCLASS.
